name: prototype_dynamic_ui
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+16
  flutter_staggered_grid_view:
  cached_network_image:

flutter:
  uses-material-design: true

  assets:
    - assets/food.json